export default [
  {
    id: 1,
    name: "Shirt 1",
    description: "",
    price: [24, 19],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["men"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 2",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["women"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 3",
    description: "",
    price: [23, 19],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["men"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 4",
    description: "",
    price: [28, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["women"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 5",
    description: "",
    price: [205, 120],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["men"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 6",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["women"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 7",
    description: "",
    price: [32, 18],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["men"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 8",
    description: "",
    price: [85, 75],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["women"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 9",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["men"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 1,
    name: "Shirt 10",
    description: "",
    price: [40, 16],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: [],
    tags: ["women"],
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  //   {
  //     id: 1,
  //     name: "Shirt 1",
  //     description: "",
  //     price: [20, 10],
  //     rating: 1,
  //     color: ["red", "black","blue"],
  //     size: { small: "s", medium: "m", large: "l" },
  //     images: [],
  //     tags: ["men"],
  //     categories: [],
  //     additionalInfo: "",
  //     reviews: [],
  //   },
];
