export default [
  {
    id: 1,
    name: "Shirt 1",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [24, 19],
    rating: 1,
    colors: ["red", "black", "blue"],
    sizes: ["s", "m", "l"],
    images: ["/assets/1.jpg", "/assets/2.jpg", "/assets/3.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 2,
    name: "Shirt 2",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [20, 10],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/2.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 3,
    name: "Shirt 3",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [23, 19],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/3.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 4,
    name: "Shirt 4",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [28, 10],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/4.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 5,
    name: "Shirt 5",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [205, 120],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/5.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 6,
    name: "Shirt 6",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [20, 10],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/6.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 90,
    name: "Shirt 6",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [20, 10],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/6.jpg"],
    tags: "bags",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 64,
    name: "Shirt 6",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [20, 10],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/6.jpg"],
    tags: "kids",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 7,
    name: "Shirt 7",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [32, 18],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/7.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 8,
    name: "Shirt 8",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [85, 75],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/8.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 9,
    name: "Shirt 9",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [20, 10],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/9.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 19,
    name: "Shirt 10",
    description:
      "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    price: [40, 16],
    rating: 1,
    colors: ["red", "black", "blue"],
    size: ["s", "m", "l"],
    images: ["/assets/10.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  //   {
  //     id: 1,
  //     name: "Shirt 1",
  //     description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
  //     price: [20, 10],
  //     rating: 1,
  //     colors: ["red", "black","blue"],
  //     size: ["s", "m", "l"],
  //     images: ["/assets/1.jpg"],
  //     tags: "men",
  //     categories: [],
  //     additionalInfo: "",
  //     reviews: [],
  //   },
];
