export default [
  {
    id: 1,
    name: "Shirt 1",
    description: "",
    price: [24, 19],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/1.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 2,
    name: "Shirt 2",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/2.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 3,
    name: "Shirt 3",
    description: "",
    price: [23, 19],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/3.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 4,
    name: "Shirt 4",
    description: "",
    price: [28, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/4.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 5,
    name: "Shirt 5",
    description: "",
    price: [205, 120],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/5.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 6,
    name: "Shirt 6",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/6.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 90,
    name: "Shirt 6",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/6.jpg"],
    tags: "bags",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 64,
    name: "Shirt 6",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/6.jpg"],
    tags: "kids",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 7,
    name: "Shirt 7",
    description: "",
    price: [32, 18],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/7.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 8,
    name: "Shirt 8",
    description: "",
    price: [85, 75],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/8.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 9,
    name: "Shirt 9",
    description: "",
    price: [20, 10],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/9.jpg"],
    tags: "men",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  {
    id: 19,
    name: "Shirt 10",
    description: "",
    price: [40, 16],
    rating: 1,
    color: ["red", "black", "blue"],
    size: { small: "s", medium: "m", large: "l" },
    images: ["assets/10.jpg"],
    tags: "women",
    categories: [],
    additionalInfo: "",
    reviews: [],
  },
  //   {
  //     id: 1,
  //     name: "Shirt 1",
  //     description: "",
  //     price: [20, 10],
  //     rating: 1,
  //     color: ["red", "black","blue"],
  //     size: { small: "s", medium: "m", large: "l" },
  //     images: ["assets/1.jpg"],
  //     tags: "men",
  //     categories: [],
  //     additionalInfo: "",
  //     reviews: [],
  //   },
];
